### ISSUE TITLE
The splash screen is revolting

### ISSUE THREAD

**Issue by Muks14x** [mayank8318/Celesta-2k17#16]
The splash screen hangs a bit, and is ugly. Needs changes.

**Comment by arihant-001** [comment]
hey , can I help u with this...

**Comment by Muks14x** [comment]
Sure, go ahead 😊. We have a deadline on this though, please proceed fast.

**Comment by arihant-001** [comment]
do u want splash image to complete full loop before exiting..

**Comment by Muks14x** [comment]
Whatever goes well with it

**Comment by arihant-001** [comment]
by revolting u mean hanging?

**Comment by arihant-001** [comment]
now its not hanging .. I have done some changes.

**Comment by Muks14x** [comment]
Updated issue, sorry about the confusion. Do whatever needs to be done to make it less ugly. Try out other splash screens if needed, or resize this one.

**Comment by arihant-001** [comment]
![screenshot_20170930-174208](https://user-images.githubusercontent.com/23583851/31045715-447d3f7c-a607-11e7-9537-49f05bea1ff2.png)
is this fine?

**Comment by Muks14x** [comment]
@mayank8318 @ivary43 What do you guys think? I okay with it, but would prefer it to be something else entirely. Can we see the code changes? Push your changes to your fork with a comment referencing this issue (#16).
